mrc-6089 Add coverage
mrc-ide/grout pull request #5
Opened 2024-12-18 12:28 UTC by EmmaLRussell

2024-12-18 14:57 UTC, M-Kusumgar requested changes
looks good, but i think that is the wrong path to server, after that happy to approve!

2024-12-18 14:57 UTC, M-Kusumgar commented on vitest.config.mts
> +            exclude: ["**/tests/**", "src/server/server.ts"]
```suggestion
            exclude: ["**/tests/**", "src/server.ts"]
```

2024-12-18 15:27 UTC, EmmaLRussell commented on vitest.config.mts
> +            exclude: ["**/tests/**", "src/server/server.ts"]
:facepalm: Thanks!

2024-12-19 10:47 UTC, M-Kusumgar approved these changes

2024-12-19 10:57 UTC, merged